version: '3.7'

services:

  nginx-front:
    image: nginx:stable-alpine
    container_name: nginx-front
    ports:
      - "${APP_PORT:-90}:80"
    volumes:
      - ./dist:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
